
export const PIZZAS = {
    pizzas: [
    {
      id: 1,
      category: "premium",
      quantity: 0,
      kilojoules: 6000,
      name: "Meatlovers",
      crust: {id: 1, name: "original_pan", display: "Original Pan", price_diff: 0},
      size: { id: 1, name: "large", display: "Large", price_diff: 0 },
      surcharges: [],
      price: 12.45,
      vegetarian: false,
      img: 'pep1.png',
      vegan: false,
      spicy: false,
      popular: true,
      description: `Steak, streaky bacon rashers, smoky honey ham, pepperoni, Italian sausage, lightly seasoned beef & mozzarella on a BBQ base with a Sweet Baby Ray's Hickory & Brown Sugar drizzle`,
    },
    {
      id: 2,
      category: "favourites",
      kilojoules: 6000,
      crust: {id: 1, name: "original_pan", display: "Original Pan", price_diff: 0},
      name: "Vego",
      surcharges: [],
      size: { id: 1, name: "large", display: "Large", price_diff: 0 },
      quantity: 0,
      price: 9.45,
      img: 'pep1.png',
      vegetarian: true,
      vegan: false,
      spicy: false,
      popular: false,
      description: `Just good old veges`,
    },
    {
      id: 3,
      category: "premium",
      kilojoules: 6000,
      crust: {id: 1, name: "original_pan", display: "Original Pan", price_diff: 0},
      surcharges: [],
      quantity: 0,
      size: { id: 1, name: "large", display: "Large", price_diff: 0 },
      name: "Chicken Prawn",
      img: 'pep1.png',
      price: 13.45,
      vegetarian: true,
      vegan: false,
      spicy: false,
      popular: false,
      description: `Sooooooo good`,
    },
    {
      id: 4,
      category: "custom",
      name: "Design your own!",
      kilojoules: 6000,
      crust: {id: 1, name: "original_pan", display: "Original Pan", price_diff: 0},
      surcharges: [],
      quantity: 0,
      size: { id: 1, name: "large", display: "Large", price_diff: 0 },
      img: 'pep1.png',
      price: 13.45,
      vegetarian: true,
      vegan: false,
      spicy: false,
      popular: false,
      description: `You design it yourself`,
    },
    {
      id: 5,
      category: "premium",
      name: "Design your own!",
      kilojoules: 6000,
      crust: {id: 1, name: "original_pan", display: "Original Pan", price_diff: 0},
      surcharges: [],
      quantity: 0,
      size: { id: 1, name: "large", display: "Large", price_diff: 0 },
      img: 'pep1.png',
      price: 13.45,
      vegetarian: true,
      vegan: false,
      spicy: false,
      popular: false,
      description: `You design it yourself`,
    },
    {
      id: 6,
      category: "premium",
      name: "Design your own!",
      crust: {id: 1, name: "original_pan", display: "Original Pan", price_diff: 0},
      kilojoules: 6000,
      size: { id: 1, name: "large", display: "Large", price_diff: 0 },
      surcharges: [],
      quantity: 0,
      img: 'pep1.png',
      price: 13.45,
      vegetarian: true,
      vegan: false,
      spicy: false,
      popular: false,
      description: `You design it yourself`,
    },
  ]}